### ISSUE TITLE
Issue running on Ubuntu Distro

### ISSUE THREAD

**Issue by Mickey374** [ashutoshkrris/Virtual-Personal-Assistant-using-Python#2]
Hello, @ashutoshkrris I had a problem testing my file after coding along in VS code but I was able to actually fix this issue. I will be glad if anyone will like me to share the experience. Thanks

**Comment by ashutoshkrris** [comment]
Sure @Mickey374 
You should surely share how you resolved the issue. It will help fellow developers during the development

**Comment by nihitgakhar** [comment]
please share your experience
it will be helpful

**Comment by Mickey374** [comment]
@nihitgakhar @ashutoshkrris 
I created a repo for this here [https://github.com/Mickey374/Virtual-Personal-Assistant-Using-Python-Ubuntu_20.04]
Kindly visit and when there are issues, we can resolve them together. Thanks to @ashutoshkrris

**Comment by nihitgakhar** [comment]
Thank you @Mickey374, it is really helpful
If there is an issue I'll let you know
